version: "3.9"

services:
  app:
    build:
      context: .
      target: dev
    container_name: crm-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      # Optionally enable these on demand
      # PRISMA_DB_PUSH: "true"      # run prisma db push at startup
      # RUN_DB_SEED: "true"         # run seed script at startup
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules

volumes:
  app-node-modules:
